name: publish-stencil-component
on: push
jobs:
  setup:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - name: Cache node_modules
        id: cache-node-modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('package-lock.json') }}
      - name: Install dependencies
        run: npm install

  build-stencil-component:
    runs-on: self-hosted
    needs: setup
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Restore node_modules
        id: cache-node-modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('package-lock.json') }}
      - run: npx nx build stencil-component
      - run: npm publish
        working-directory: ./dist/libs/stencil-component
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  build-stencil-component-react:
    runs-on: self-hosted
    needs: setup
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Restore node_modules
        id: cache-node-modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('package-lock.json') }}
      - run: npx nx build stencil-component-react
      - run: npm publish
        working-directory: ./dist/libs/stencil-component-react
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  build-stencil-component-angular:
    runs-on: self-hosted
    needs: setup
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Restore node_modules
        id: cache-node-modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('package-lock.json') }}
      - run: npx nx build stencil-component-angular
      - run: npm publish
        working-directory: ./dist/libs/stencil-component-angular
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

