name: Packages Publishing

on:
  release:
    types: [published]

# on:
#   push:
#     branches: [develop]

jobs:
  setup:
    runs-on: ubuntu-18.04
    steps:
      - name: Cancel previous redundant builds
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
      - name: Symbol - Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Release version
        run: echo ${{ github.event.release.tag_name }}
      - name: Setup node
        uses: ./.github/actions/cache-node-modules

  build-stencil:
    needs: [setup]
    runs-on: ubuntu-18.04
    steps:
      - name: Symbol - Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.release.target_commitish }}
          submodules: recursive
      - name: Setup
        uses: ./.github/actions/setup
      - name: Get current package version
        run: node -p "require('./package.json').version"
        working-directory: ./libs/stencil-component
      - name: Update package version
        run: npm version ${{ github.event.release.tag_name }}
        working-directory: ./libs/stencil-component
      - name: Build stencil components
        run: npx nx build stencil-component
      - name: Get package version after building
        run: node -p "require('./package.json').version"
        working-directory: ./dist/libs/stencil-component
      - name: Upload changes to the repository
        run: |
          git config --global user.name "Dynamic bot"
          git config --global user.email "info@dynamicdevs.io"
          git push
        env:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload build files
        uses: actions/upload-artifact@v3
        with:
          name: stencil-component
          path: dist/libs/stencil-component

  deploy-stencil:
    needs: [build-stencil]
    runs-on: ubuntu-18.04
    steps:
      - name: Symbol - Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Setup
        uses: ./.github/actions/setup
      - name: Download build files
        uses: actions/download-artifact@v3
        with:
          name: stencil-component
          path: dist
      - name: Publish stencil-component
        run: npm publish
        working-directory: ./dist
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
