name: Symbols Pipeline

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]
    types: [opened, synchronize]

jobs:
  reduncy:
    runs-on: ubuntu-18.04
    steps:
      - name: Cancel Previous Redundant Builds
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
  setup:
    runs-on: ubuntu-18.04
    steps:
      - name: Symbol - Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - name: Cache node_modules
        id: cache-node-modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('package-lock.json') }}
      - name: Install dependencies
        run: npm ci

  build-stencil:
    runs-on: ubuntu-18.04
    steps:
      - name: Symbol - Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - name: Restore node_modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('package-lock.json') }}
      - name: Build Stencil Components
        run: npx nx build stencil-component
